---
title: Правила хорошего кода
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    theme: simplex
    highlight: haddock
    include:
      after_body: _footer.html
    css: my_styles.css
---

<span style="color: red; font-size:20pt">
Это архивная версия курса. Последний раз таким составом авторов курс был прочитан осенью 2022г.</span>

Современная версия [здесь](https://polydora.github.io/linmodr/)

---

Правила хорошего кода - это правила, которых стоит придерживаться, чтобы ваш код через какое-то время смог прочесть и легко понять кто-то другой или вы сами. Поэтому хорошо, если ваш код разделен на логические блоки и в достаточной степени прокомментирован.

Существующие практики различаются в деталях. Например, когда названия переменных и функций написаны единообразно, их легче прочесть и понять, чем они занимаются. 

Google [рекомендует](https://google.github.io/styleguide/Rguide.xml) использовать для этих идентификаторов `верблюжийРегистр` -  [`camelCase`](http://ru.wikipedia.org/wiki/CamelCase). 

Автор графического пакета [`ggplot2`](http://www.ggplot2.org/), [Хэдли Викхем](http://had.co.nz/), [рекомендует](http://stat405.had.co.nz/r-style.html) `стиль_через_подчёркивание`, наверное, из-за `легкости_чтения_многословных_названий`. 

Бывает смешаный стиль: `названияПеременных` и `названия_функций`.

У Хэдли Викхема собраны только самые необходимые правила хорошего кода - достаточно для программирования на лекциях. Что касается названий переменных, выбирайте по вашему усмотрению. За последовательное применение `camelCase` санкций не будет:)

- [Hadley Wickham Style guide. stat405 - fall 2012, Rice University, USA](http://stat405.had.co.nz/r-style.html)
- [Google’s R Style Guide](https://google.github.io/styleguide/Rguide.xml)
