---
title: Критерии оценки домашних заданий
---

[Пример решения домашнего задания](example_task.zip).

Минимальный набор файлов в решенном домашнем задании --- код и отчет.

## Требования к коду

Код - это программа, выполнив которую, можно воспроизвести ваши результаты (с минимальной заменой путей к файлам с исходными данными). Внимание: код прикладывайте в виде отдельного файла .R, без вывода консоли!

- [Правила хорошего кода](coding_practices.md)

## Требования к отчету

Отчет должен быть выдержан в форме научной мини-статьи.

Разделы:

- Введение --- Объясните, зачем затевалось исследование и почему оно важно. Сформулируйте исследовательский вопрос и гипотезы, которые необходимо проверить. (Кратко, 2-5 предложений)
- Материалы и методы --- Объясните, что и зачем делали во время исследования. Опишите дизайн исследования, особенности данных, порядок применения статистических методов. Например, здесь стоит сказать, какие условия применимости методов вы проверяли и каким способом, что показали результаты проверки и как они повлияли на дальнейший анализ. Обязательно должны быть ссылки на литературу с описанием метода, на использованные статистические пакеты. (Этот пункт запросто может занять пару-тройку абзацев).
- Результаты и обсуждение --- Визуализируйте результаты, опишите и поясните их, по возможности, кратко. Описание результатов статистических тестов можно давать в скобках в тексте, в виде таблиц. У рисунков и таблиц должны быть осмысленные подписи, и в тексте на них должны быть ссылки.
- Выводы --- Сформулируйте выводы.
- Список литературы

## Оценки 

Качество отчета оценивается по анкете. Оценки за каждый из пунктов: 1/3 балла - да, все, что нужно; 1/6 балла - да, но не все, что нужно; 0 - нет/ничего. За 6 выполненных заданий можно набрать $1/3 \times 15 \times 6 = 30$ баллов, плюс еще 6 дополнительных, если задание сдано в срок.

Анкета для оценки заданий составлена по мотивам критериев оценки от [Джеффа Лика](http://www.biostat.jhsph.edu/~jleek/research.html) в курсе Data Analysis на [Coursera](http:/coursera.org).

### Анкета, по которой оценивается домашнее задание

Оценка ХХ + ХХ = XX из 5 возможных баллов

#### A. Самостоятельность выполнения задания.

1. Самостоятельно ли написан текст домашнего задания? В случае обнаружения явных заимствований или не оформленных цитат все баллы "сгорают"

#### B. Описание анализа данных и результатов

1. Есть ли в отчете разделы (Введение, Материалы и методы, Результаты и Обсуждение, Выводы, Список литературы) и соответствует ли их содержание заголовкам?
2. Описаны ли в тексте вопросы, на которые нужно дать ответ или гипотезы, которые нужно проверить?
3. Описаны ли в тексте особенности применения статистических методов?
4. Содержит ли текст ссылки на использованные статистические методы и программное обеспечение?
5. Упоминаются ли переменные простыми словами, а не кодовыми наименованиями?
6. Указаны ли объемы выборок?
7. Корректно ли применены статистические процедуры?
8. Правильно ли интерпретированы результаты анализа?
9. Сделаны ли конкретные выводы из анализа?
10. Есть ли в тексте пронумерованные ссылки на рисунки и таблицы?

#### C. Рисунки, таблицы и подписи

1. Достаточно ли подписи к рисунку/таблице, чтобы можно было понять его в отрыве от основного текста?
2. Подписаны ли на рисунке оси, достаточно ли велик шрифт, чтобы его было удобно читать?

#### D. R-код

1. Разделен ли код на логические блоки примечаниями?
2. Можно ли воспроизвести анализ при помощи приложенного кода? 

