---
title: Линейные модели, дисперсионный и регрессионный анализ с использованием R
tagline: Презентации к курсу
description: Презентации к курсу Линейные модели, дисперсионный и регрессионный анализ с использованием R
---
 
## О курсе

### Цель и задачи курса

Курс знакомит с применением различных вариантов линейных моделей в биологии (регрессионный анализ, анализ ковариаций, дисперсионный анализ, логистическая регрессия, смешанные линейные модели). В итоге, вы сможете критически оценивать корректность применения методов статистики в научных статьях, самостоятельно анализировать данные с использованием скриптов на языке статистического программирования R, представлять в наглядном виде результаты анализов, интерпретировать их и представлять в виде научного отчета.

### Расписание и контакты

#### Расписание:

#### Office hours: 

#### Инструкторы: 

- Варфоломеева Марина Александровна -  marina.nikolaeva[]gmail.com
- Хайтов Вадим Михайлович - polydora[]rambler.ru
- Тамберг Юта Юрьевна - yutamberg[]gmail.com

### Задания, дедлайны и оценки

(1) Короткие тесты (10 минут) в начале каждой лекции, кроме самой первой --- 30 баллов. Каждый тест из 5 вопросов на каждом занятии, кроме первого, т.е. всего 75 вопросов. Каждый правильный ответ приносит 0.4 балла.

(2) Домашние задания по анализу данных --- 30 баллов. Срок выполнения --- 2 недели (прислать по e-mail). За каждое домашнее задание можно получить 5 баллов. За сданное в срок задание один дополнительный балл (т.е. 36 баллов за 6 правильных заданий в срок). Минимальный набор файлов в решенном задании --- это отчет и код.

- [Критерии оценки домашних заданий](evaluation_criteria.html)
- [Пример решения домашнего задания](example-report.zip)
- [Правила хорошего кода](coding_practices.html)

(3) В конце курса будет финальный тест --- 40 баллов (всего 20 вопросов, каждый правильный ответ приносит 2 балла).

Итоговая оценка:

- Выше 60 баллов - зачет
- 60-69 баллов => «удовлетворительно»; 70-79% => «хорошо»; 80 и больше => «отлично»

### Пересдачи заданий

Пропущенные тесты можно будет решить в конце курса.
Три из уже сделанных тестов на выбор можно будет перерешать.


## Ссылки и ресурсы

- [Исходный код в RMarkdown](http://github.com/varmara/linmodr-course)
- [Другие ресурсы и книги для изучения R и статистики](resources.html)

<!--

- [Как и где можно найти помощь с R и статистикой](more_help.html)

-->

---

## Презентации

1. [Знакомство с R](01_introduction_to_r.html)
2. [Тестирование гипотез](02_hypothesis_testing.html)
3. [Анализ мощности](03_power_analysis.html)
4. [Простая линейная регрессия](04_linear_regression.html)
5. [Проверка условий применимости регрессионных моделей](05_diagnostics_of_regression_models.html)
6. [Множественная линейная регрессия](06_multiple_linear_regression.html)
7. [Сравнение линейных моделей](07_model_selection.html)
8. [Линейные модели с непрерывными и дискретными предикторами](08_linear_regression_with_continuous_and_discreet_predictors.html)
9. [Линейные модели только с дискретными предикторами (дисперсионный анализ)](09_anova.html)
10. [Многофакторный дисперсионный анализ](10_two-way_anova_and_interactions.html)
11. [Линейные модели для бинарных данных (логистическая регрессия)](11_general_linear_models_for_binary_data.html)
12. [Линейные модели для счетных данных](12_general_linear_models_for_count_data.html)
13. [Смешанные линейные модели](13_general_linear_mixed_models.html)
14. [Коррекция гетерогенности дисперсий в смешанных линейных моделях](14_modelling_variance_structure.html)
15. [Обобщенные смешанные линейные модели для бинарных данных](15_general_linear_mixed_models_for_binary_data.html)
16. [Обобщенные смешанные модели для счетных данных](16_general_linear_mixed_models_for_count_data.html)

